services:
  - type: web
    name: cretivra-ai
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: OLLAMA_BASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: UPI_ID
        value: suhashsugi369-1@oksbi
      - key: UPI_NAME
        value: SUHASH MAHADEVA

