'use client';

import React from 'react';
import type { AwakeningStage } from './useOpeningTimeline';

interface AsuraIdentityProps {
  stage: AwakeningStage;
}

export const AsuraIdentity: React.FC<AsuraIdentityProps> = ({ stage }) => {
  const showIdentity = stage === 'IDENTITY' || stage === 'TRANSITION';

  return (
    <div className="relative mt-8 flex flex-col items-center justify-center select-none pointer-events-none z-25">
      {/* 1. Coherent Luminous Horizontal Laser Line generated by core */}
      <div className="relative w-64 sm:w-80 h-[1.5px] flex items-center justify-center overflow-hidden">
        <div
          className={`h-full bg-gradient-to-r from-transparent via-cyan-400 to-transparent filter drop-shadow-[0_0_10px_rgba(6,182,212,0.9)] transition-all duration-700 ${
            showIdentity ? 'w-full opacity-100 asura-animate-laser' : 'w-0 opacity-0'
          }`}
          aria-hidden="true"
        />
      </div>

      {/* 2. Dominant, Confident ASURA Wordmark */}
      <div className="relative mt-4 flex flex-col items-center text-center">
        <div className="relative overflow-hidden inline-block px-6 py-1">
          <h1
            className={`text-4xl sm:text-5xl font-black text-[#030712] font-sans transition-all duration-700 ${
              showIdentity ? 'asura-animate-wordmark' : 'opacity-0'
            }`}
            style={{
              letterSpacing: showIdentity ? '0.16em' : '0.38em',
              textShadow: '0 2px 20px rgba(6, 182, 212, 0.25)',
            }}
          >
            ASURA
          </h1>

          {/* Prismatic Light Sweep Across Letterforms */}
          {showIdentity && (
            <div
              className="absolute inset-0 w-full h-full asura-animate-sweep bg-gradient-to-r from-transparent via-white/85 to-transparent pointer-events-none"
              aria-hidden="true"
            />
          )}
        </div>

        {/* Refined Enterprise Subtitle (No generic SaaS AI Pill!) */}
        <p
          className={`mt-1.5 text-[10px] sm:text-[11px] font-semibold tracking-[0.28em] uppercase text-slate-500 font-sans pl-[0.28em] transition-all duration-700 ${
            showIdentity ? 'asura-animate-subtitle' : 'opacity-0'
          }`}
        >
          FRONTIER INTELLIGENCE • BY CRETIVRA
        </p>
      </div>
    </div>
  );
};

