'use client';

import React from 'react';
import type { AwakeningStage } from './useOpeningTimeline';

interface AsuraIdentityProps {
  stage: AwakeningStage;
}

export const AsuraIdentity: React.FC<AsuraIdentityProps> = ({ stage }) => {
  const showIdentity = stage === 'IDENTITY' || stage === 'TRANSITION';

  return (
    <div className="relative mt-7 flex flex-col items-center justify-center select-none pointer-events-none z-25">
      {/* 1. Coherent Luminous Horizontal Laser Line generated by core */}
      <div
        className={`h-[1.5px] bg-gradient-to-r from-transparent via-cyan-400 to-transparent transition-all duration-600 ease-out filter drop-shadow-[0_0_8px_rgba(6,182,212,0.8)] ${
          showIdentity ? 'w-56 sm:w-72 opacity-95 asura-animate-laser' : 'w-0 opacity-0'
        }`}
        aria-hidden="true"
      />

      {/* 2. Dominant, Confident ASURA Wordmark */}
      <div
        className={`relative mt-3.5 flex flex-col items-center text-center transition-all duration-600 ease-out ${
          showIdentity
            ? 'opacity-100 translate-y-0 filter blur-none'
            : 'opacity-0 translate-y-3 filter blur-md'
        }`}
        style={{
          transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
        }}
      >
        <div className="relative overflow-hidden inline-block px-4 py-1">
          <h1
            className="text-3xl sm:text-4xl font-extrabold tracking-[0.16em] text-[#0a1128] font-sans pl-[0.16em]"
            style={{ letterSpacing: '0.16em' }}
          >
            ASURA
          </h1>

          {/* Prismatic Light Sweep Across Letterforms */}
          {showIdentity && (
            <div
              className="absolute inset-0 w-full h-full asura-animate-sweep bg-gradient-to-r from-transparent via-white/80 to-transparent pointer-events-none"
              aria-hidden="true"
            />
          )}
        </div>

        {/* Refined Enterprise Subtitle (No generic SaaS AI Pill!) */}
        <p
          className="mt-1 text-[10px] sm:text-[11px] font-semibold tracking-[0.25em] uppercase text-slate-500 font-sans pl-[0.25em]"
          style={{ letterSpacing: '0.25em' }}
        >
          FRONTIER INTELLIGENCE • BY CRETIVRA
        </p>
      </div>
    </div>
  );
};
