'use client';

import React from 'react';
import type { AwakeningStage } from './useOpeningTimeline';

interface AsuraIdentityProps {
  stage: AwakeningStage;
}

export const AsuraIdentity: React.FC<AsuraIdentityProps> = ({ stage }) => {
  const showIdentity =
    stage === 'IDENTITY' || stage === 'TRANSITION';

  return (
    <div className="relative mt-6 flex flex-col items-center justify-center select-none pointer-events-none z-25">
      {/* 1. Thin Horizontal Luminous Light Field generated by the core */}
      <div
        className={`h-[1px] bg-gradient-to-r from-transparent via-cyan-400 to-transparent transition-all duration-700 ease-out ${
          showIdentity ? 'w-48 sm:w-64 opacity-80' : 'w-0 opacity-0'
        }`}
        aria-hidden="true"
      />

      {/* 2. ASURA Typography Materialization with Letterform Sweep */}
      <div
        className={`relative mt-3 flex flex-col items-center text-center transition-all duration-500 ease-out ${
          showIdentity
            ? 'opacity-100 translate-y-0 filter blur-none'
            : 'opacity-0 translate-y-2 filter blur-md'
        }`}
        style={{
          transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
        }}
      >
        {/* Dominant Clean, Confident ASURA Brand Wordmark */}
        <div className="relative overflow-hidden inline-block">
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-[#0a1128] font-sans">
            ASURA
          </h1>

          {/* Light Sweep Across Letterforms */}
          {showIdentity && (
            <div
              className="absolute inset-0 w-full h-full asura-animate-sweep bg-gradient-to-r from-transparent via-white/70 to-transparent pointer-events-none"
              aria-hidden="true"
            />
          )}
        </div>

        {/* Refined Subtle Subtitle (No generic SaaS AI Pill!) */}
        <p className="mt-1 text-[11px] sm:text-xs font-semibold tracking-[0.2em] uppercase text-slate-500 font-sans">
          BY CRETIVRA
        </p>
      </div>
    </div>
  );
};
