import React, { useState } from 'react';
import { X, Presentation, Sparkles, Download, ArrowRight, Loader2, CheckCircle } from 'lucide-react';
import { generatePresentationApi } from '../../services/api';

interface SlideGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onGenerateWithAgent: (prompt: string) => void;
}

const PRESET_TOPICS = [
  {
    title: 'Autonomous AI Agents Architecture',
    slides: 5,
    description: 'System design, reasoning loops, tool calling, and human-in-the-loop oversight.',
  },
  {
    title: 'SaaS Investor Pitch Deck',
    slides: 8,
    description: 'Problem, solution, market size, business model, traction, and roadmap.',
  },
  {
    title: 'Quarterly Business Review (QBR)',
    slides: 6,
    description: 'Executive summary, revenue milestones, operational KPIs, and Q4 priorities.',
  },
  {
    title: 'Product Launch Strategy',
    slides: 5,
    description: 'Target personas, go-to-market channels, positioning, and rollout timeline.',
  },
];

export function SlideGeneratorModal({ isOpen, onClose, onGenerateWithAgent }: SlideGeneratorModalProps) {
  const [topic, setTopic] = useState('');
  const [slideCount, setSlideCount] = useState(5);
  const [theme, setTheme] = useState('Modern Dark');
  const [isExportingPptx, setIsExportingPptx] = useState(false);
  const [exportSuccess, setExportSuccess] = useState<string | null>(null);
  const [exportError, setExportError] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleDownloadPptx = async () => {
    const finalTopic = topic.trim() || 'Executive Strategy Presentation';
    setIsExportingPptx(true);
    setExportError(null);
    setExportSuccess(null);

    try {
      const slidesData = [
        {
          title: `Executive Overview: ${finalTopic}`,
          bullets: [
            'Market background, strategic imperatives, and key objectives.',
            'Current industry benchmark and operational opportunity.',
            'Target performance criteria and implementation scope.',
          ],
        },
        {
          title: 'Strategic Architecture & Framework',
          bullets: [
            'End-to-end operational pipeline with autonomous capability layers.',
            'Cross-functional integration points across internal systems.',
            'Risk mitigation and compliance guardrails.',
          ],
        },
        {
          title: 'Key Milestones & Implementation',
          bullets: [
            'Phase 1: Foundation audit and prototype validation.',
            'Phase 2: Scaled deployment and real-time observability.',
            'Phase 3: Automated iteration and enterprise expansion.',
          ],
        },
        {
          title: 'Metrics, ROI & Business Impact',
          bullets: [
            'Projected 65% reduction in manual turnaround cycles.',
            'Measurable efficiency gains and cost containment.',
            'High-confidence scalability metrics across key teams.',
          ],
        },
        {
          title: 'Conclusion & Next Steps',
          bullets: [
            'Immediate deployment action items for the upcoming sprint.',
            'Resource allocation and governance oversight.',
            'Ongoing measurement, feedback, and refinement.',
          ],
        },
      ].slice(0, slideCount);

      const res = await generatePresentationApi({
        title: finalTopic,
        subtitle: `Generated by Asura AI Presentation Engine • Theme: ${theme}`,
        slides: slidesData,
        theme,
      });

      if (res?.download_url) {
        setExportSuccess(`Created "${res.filename}" (${res.slide_count} slides)`);
        const a = document.createElement('a');
        a.href = res.download_url;
        a.download = res.filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
      } else {
        throw new Error('No download URL returned from presentation service');
      }
    } catch (err: any) {
      console.warn('PPTX export fallback:', err);
      setExportError(err.message || 'Direct PPTX generation unavailable. Try Generate with AI Agent.');
    } finally {
      setIsExportingPptx(false);
    }
  };

  const handleLaunchAgent = () => {
    const finalTopic = topic.trim() || 'Autonomous AI Agents Architecture';
    const prompt = `Create a professional ${slideCount}-slide presentation deck on "${finalTopic}". Include:
1. Title slide with subtitle and presenter metadata.
2. Executive Summary and problem context.
3. Key strategic pillars with clear bullet points.
4. Implementation architecture & timeline.
5. Projected ROI, metrics, and conclusion.
Format each slide with clean slide titles, 3-4 high-impact bullets, and suggested visual layouts for presentation slides.`;
    onGenerateWithAgent(prompt);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in duration-150">
      <div className="relative w-full max-w-xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-3xl p-6 sm:p-7 shadow-2xl text-gray-900 dark:text-gray-100 overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-gray-100 dark:border-gray-800">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-amber-50 dark:bg-amber-950/50 border border-amber-200 dark:border-amber-800/60 flex items-center justify-center text-amber-600 dark:text-amber-400">
              <Presentation size={18} />
            </div>
            <div>
              <h3 className="text-base font-semibold">Create Presentation Slides</h3>
              <p className="text-xs text-gray-500 dark:text-gray-400">AI-powered slide deck generator &amp; PPTX export</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 transition-colors cursor-pointer"
          >
            <X size={18} />
          </button>
        </div>

        {/* Form Body */}
        <div className="py-5 space-y-4">
          <div>
            <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1.5">
              Presentation Topic or Goal
            </label>
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g., Autonomous AI Agents in Enterprise Operations"
              className="w-full px-3.5 py-2.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/70 text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 dark:focus:ring-white transition-all placeholder:text-gray-400"
            />
          </div>

          {/* Quick Presets */}
          <div>
            <span className="block text-[11px] font-semibold uppercase tracking-wider text-gray-400 dark:text-gray-500 mb-2">
              Popular Presets
            </span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {PRESET_TOPICS.map((preset) => (
                <button
                  key={preset.title}
                  type="button"
                  onClick={() => {
                    setTopic(preset.title);
                    setSlideCount(preset.slides);
                  }}
                  className={`p-2.5 rounded-xl border text-left text-xs transition-all cursor-pointer ${
                    topic === preset.title
                      ? 'border-amber-500 bg-amber-50/50 dark:bg-amber-950/20 text-amber-900 dark:text-amber-200'
                      : 'border-gray-200 dark:border-gray-800 hover:border-gray-300 dark:hover:border-gray-700 bg-white dark:bg-gray-800/40'
                  }`}
                >
                  <span className="font-semibold block truncate">{preset.title}</span>
                  <span className="text-[11px] text-gray-500 dark:text-gray-400 block truncate mt-0.5">
                    {preset.slides} slides • {preset.description}
                  </span>
                </button>
              ))}
            </div>
          </div>

          {/* Configuration Grid */}
          <div className="grid grid-cols-2 gap-3 pt-1">
            <div>
              <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1.5">
                Number of Slides
              </label>
              <div className="flex gap-1.5">
                {[3, 5, 8, 10].map((num) => (
                  <button
                    key={num}
                    type="button"
                    onClick={() => setSlideCount(num)}
                    className={`flex-1 py-1.5 rounded-lg text-xs font-medium border transition-all cursor-pointer ${
                      slideCount === num
                        ? 'bg-gray-900 text-white dark:bg-white dark:text-gray-900 border-transparent shadow-xs'
                        : 'border-gray-200 dark:border-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800'
                    }`}
                  >
                    {num}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-xs font-medium text-gray-700 dark:text-gray-300 mb-1.5">
                Visual Theme
              </label>
              <select
                value={theme}
                onChange={(e) => setTheme(e.target.value)}
                className="w-full px-3 py-1.5 rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/70 text-xs focus:outline-none"
              >
                <option value="Modern Dark">Modern Dark</option>
                <option value="Clean Minimalist">Clean Minimalist</option>
                <option value="Ocean Blue">Ocean Blue</option>
                <option value="Sunset Gradient">Sunset Gradient</option>
              </select>
            </div>
          </div>

          {/* Feedback Messages */}
          {exportSuccess && (
            <div className="flex items-center gap-2 p-3 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800 text-xs text-emerald-800 dark:text-emerald-300">
              <CheckCircle size={15} className="shrink-0" />
              <span>{exportSuccess} - Download started!</span>
            </div>
          )}
          {exportError && (
            <div className="p-3 rounded-xl bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 text-xs text-rose-700 dark:text-rose-300">
              {exportError}
            </div>
          )}
        </div>

        {/* Actions Footer */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-4 border-t border-gray-100 dark:border-gray-800">
          <button
            type="button"
            onClick={handleDownloadPptx}
            disabled={isExportingPptx}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800 text-xs font-semibold text-gray-800 dark:text-gray-200 transition-all disabled:opacity-50 cursor-pointer"
          >
            {isExportingPptx ? (
              <>
                <Loader2 size={14} className="animate-spin" />
                <span>Exporting PPTX...</span>
              </>
            ) : (
              <>
                <Download size={14} />
                <span>Download .PPTX</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={handleLaunchAgent}
            className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-gray-900 hover:bg-black dark:bg-white dark:hover:bg-gray-100 text-white dark:text-gray-900 text-xs font-semibold shadow-md transition-all cursor-pointer"
          >
            <Sparkles size={14} />
            <span>Generate Slides with AI</span>
            <ArrowRight size={14} />
          </button>
        </div>
      </div>
    </div>
  );
}
