import React, { useEffect, useState } from 'react';
import {
  Files,
  RotateCw,
  Search,
  FileText,
  Presentation,
  FileSpreadsheet,
  FileCode,
  Globe,
  Download,
  Eye,
  Share2,
  Check,
  ImageIcon,
  X,
  ExternalLink,
} from 'lucide-react';
import { listArtifactsApi, resolveArtifactDownloadUrl, getArtifactContentApi, type Artifact } from '../../services/playgroundApi';

interface ArtifactsWorkspaceProps {
  onPreviewArtifact?: (art: Artifact) => void;
}

export function ArtifactsWorkspace({ onPreviewArtifact }: ArtifactsWorkspaceProps) {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [filter, setFilter] = useState<string>('all');
  const [search, setSearch] = useState('');
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [previewingArt, setPreviewingArt] = useState<Artifact | null>(null);
  const [previewContent, setPreviewContent] = useState<string | null>(null);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);

  const fetchArtifacts = async () => {
    setIsLoading(true);
    try {
      const data = await listArtifactsApi();
      setArtifacts(data);
    } catch (e) {
      console.error('Failed to load artifacts:', e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchArtifacts();
  }, []);

  const handleCopyLink = (art: Artifact) => {
    const url = resolveArtifactDownloadUrl(art.download_url);
    navigator.clipboard.writeText(window.location.origin + url);
    setCopiedId(art.id);
    setTimeout(() => setCopiedId(null), 1500);
  };

  const handleOpenPreview = async (art: Artifact) => {
    if (onPreviewArtifact) {
      onPreviewArtifact(art);
      return;
    }
    setPreviewingArt(art);
    setIsLoadingPreview(true);
    setPreviewContent(null);
    try {
      const text = await getArtifactContentApi(art.download_url);
      setPreviewContent(text);
    } catch (err) {
      setPreviewContent('Preview not directly renderable or binary content.');
    } finally {
      setIsLoadingPreview(false);
    }
  };

  const getArtifactIcon = (type: string, name: string) => {
    const upper = (type || '').toUpperCase();
    if (upper === 'PDF' || name.endsWith('.pdf')) {
      return <FileText size={18} className="text-rose-500" />;
    }
    if (upper === 'PPTX' || name.endsWith('.pptx')) {
      return <Presentation size={18} className="text-amber-500" />;
    }
    if (upper === 'CSV' || upper === 'XLSX' || name.endsWith('.csv') || name.endsWith('.xlsx')) {
      return <FileSpreadsheet size={18} className="text-emerald-500" />;
    }
    if (upper === 'WEBSITE' || name.endsWith('.html') || name.endsWith('.htm')) {
      return <Globe size={18} className="text-[#06B6D4]" />;
    }
    if (upper === 'IMAGE' || name.endsWith('.png') || name.endsWith('.jpg') || name.endsWith('.webp')) {
      return <ImageIcon size={18} className="text-violet-500" />;
    }
    return <FileCode size={18} className="text-blue-500" />;
  };

  const filtered = artifacts.filter((a) => {
    const matchesFilter =
      filter === 'all'
        ? true
        : a.type.toLowerCase().includes(filter.toLowerCase()) ||
          a.name.toLowerCase().endsWith(filter.toLowerCase());
    const matchesSearch =
      a.name.toLowerCase().includes(search.toLowerCase()) ||
      a.type.toLowerCase().includes(search.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  const filterTabs = ['all', 'PDF', 'PPTX', 'HTML', 'CSV', 'IMAGES', 'CODE'];

  return (
    <div className="flex-1 flex flex-col h-full bg-[var(--background)] text-[var(--foreground)] overflow-hidden p-6 lg:p-8 transition-colors duration-200">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 mb-6 flex-wrap">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-[var(--foreground)]">Artifacts & Deliverables</h1>
          <p className="text-xs text-[var(--muted-foreground)] mt-1">
            Browse and download documents, slide decks, and code generated by Asura.
          </p>
        </div>

        <button
          onClick={fetchArtifacts}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[var(--surface)] border border-[var(--border)] text-xs text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors shadow-xs cursor-pointer"
          title="Refresh artifacts"
        >
          <RotateCw size={13} className={isLoading ? 'animate-spin' : ''} />
          <span>Refresh</span>
        </button>
      </div>

      {/* Filters and Search */}
      <div className="flex items-center justify-between gap-3 mb-6 flex-wrap">
        <div className="flex items-center gap-1 bg-[var(--surface-secondary)] p-1 rounded-xl border border-[var(--border)]">
          {filterTabs.map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`px-3 py-1 rounded-lg text-xs font-medium capitalize transition-all cursor-pointer ${
                filter === tab
                  ? 'bg-[var(--surface)] text-[var(--foreground)] font-semibold shadow-xs border border-[var(--border)]'
                  : 'text-[var(--muted-foreground)] hover:text-[var(--foreground)]'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-64">
          <Search size={13} className="absolute left-3 top-2.5 text-[var(--muted-foreground)]" />
          <input
            type="text"
            placeholder="Search deliverables..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-8 pr-3 py-1.5 bg-[var(--surface-secondary)] border border-[var(--border)] rounded-xl text-xs text-[var(--foreground)] placeholder-[var(--muted-foreground)] focus:outline-none focus:border-[#06B6D4]/40"
          />
        </div>
      </div>

      {/* Artifacts Grid */}
      <div className="flex-1 overflow-y-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {isLoading ? (
          <div className="col-span-full p-12 text-center text-xs text-[var(--muted-foreground)]">
            Loading deliverables...
          </div>
        ) : filtered.length === 0 ? (
          <div className="col-span-full p-12 text-center text-xs text-[var(--muted-foreground)] rounded-2xl border border-dashed border-[var(--border)] bg-[var(--surface)]">
            No deliverables found. Deliverables are generated automatically when Asura executes tasks.
          </div>
        ) : (
          filtered.map((art) => {
            const downloadUrl = resolveArtifactDownloadUrl(art.download_url);
            const isCopied = copiedId === art.id;

            return (
              <div
                key={art.id}
                className="p-4 rounded-2xl bg-[var(--surface)] border border-[var(--border)] hover:border-[#06B6D4]/40 hover:shadow-sm transition-all flex flex-col justify-between group"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <div className="w-9 h-9 rounded-xl bg-[var(--surface-secondary)] border border-[var(--border)] flex items-center justify-center">
                      {getArtifactIcon(art.type, art.name)}
                    </div>
                    <span className="font-mono text-[10px] px-2 py-0.5 bg-[var(--surface-secondary)] rounded-md border border-[var(--border)] uppercase font-medium text-[var(--muted-foreground)]">
                      {art.type}
                    </span>
                  </div>

                  <h3 className="text-xs font-semibold text-[var(--foreground)] group-hover:text-[#06B6D4] transition-colors truncate">
                    {art.name}
                  </h3>
                  <div className="text-[11px] text-[var(--muted-foreground)] mt-1 flex items-center gap-2">
                    {art.size > 0 && <span>{(art.size / 1024).toFixed(1)} KB</span>}
                    <span>•</span>
                    <span className="text-emerald-500 font-medium">Verified</span>
                  </div>
                </div>

                <div className="mt-4 pt-3 border-t border-[var(--border)] flex items-center justify-between">
                  <button
                    onClick={() => handleOpenPreview(art)}
                    className="flex items-center gap-1 text-[11px] font-medium text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors cursor-pointer"
                  >
                    <Eye size={13} />
                    <span>Preview</span>
                  </button>

                  <div className="flex items-center gap-1">
                    <button
                      onClick={() => handleCopyLink(art)}
                      className="p-1.5 rounded-lg text-[var(--muted-foreground)] hover:text-[var(--foreground)] hover:bg-[var(--surface-secondary)] transition-colors cursor-pointer"
                      title="Copy Link"
                    >
                      {isCopied ? <Check size={13} className="text-emerald-500" /> : <Share2 size={13} />}
                    </button>

                    <a
                      href={downloadUrl}
                      download={art.name}
                      className="flex items-center gap-1 px-2 py-1 rounded-lg bg-[var(--surface-secondary)] hover:bg-[#06B6D4]/10 text-[#06B6D4] text-xs font-semibold border border-[var(--border)] transition-colors"
                      title="Download Deliverable"
                    >
                      <Download size={13} />
                      <span className="text-[11px]">Download</span>
                    </a>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Built-in Preview Modal */}
      {previewingArt && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="w-full max-w-4xl max-h-[85vh] bg-[var(--surface)] border border-[var(--border)] rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
            {/* Modal Header */}
            <div className="p-4 border-b border-[var(--border)] flex items-center justify-between">
              <div className="flex items-center gap-2.5 min-w-0">
                <div className="w-7 h-7 rounded-lg bg-[var(--surface-secondary)] border border-[var(--border)] flex items-center justify-center">
                  {getArtifactIcon(previewingArt.type, previewingArt.name)}
                </div>
                <div className="min-w-0">
                  <h3 className="text-xs font-semibold text-[var(--foreground)] truncate">{previewingArt.name}</h3>
                  <span className="text-[10px] text-[var(--muted-foreground)] font-mono uppercase">{previewingArt.type}</span>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <a
                  href={resolveArtifactDownloadUrl(previewingArt.download_url)}
                  download={previewingArt.name}
                  className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900 text-xs font-semibold hover:opacity-90 transition-opacity"
                >
                  <Download size={12} />
                  <span>Download</span>
                </a>
                <button
                  onClick={() => setPreviewingArt(null)}
                  className="p-1.5 rounded-lg text-[var(--muted-foreground)] hover:text-[var(--foreground)] hover:bg-[var(--surface-secondary)] transition-colors"
                >
                  <X size={15} />
                </button>
              </div>
            </div>

            {/* Modal Content */}
            <div className="flex-1 overflow-auto p-4 bg-[var(--background)]">
              {isLoadingPreview ? (
                <div className="p-12 text-center text-xs text-[var(--muted-foreground)]">Loading preview...</div>
              ) : previewingArt.name.endsWith('.html') || previewingArt.type.toUpperCase() === 'WEBSITE' ? (
                <iframe
                  title={previewingArt.name}
                  srcDoc={previewContent || ''}
                  sandbox="allow-scripts allow-forms allow-same-origin"
                  className="w-full h-[60vh] border rounded-xl bg-white"
                />
              ) : previewingArt.name.match(/\.(png|jpg|jpeg|webp|gif|svg)$/i) ? (
                <div className="flex items-center justify-center p-4">
                  <img
                    src={resolveArtifactDownloadUrl(previewingArt.download_url)}
                    alt={previewingArt.name}
                    className="max-h-[60vh] rounded-xl object-contain shadow-sm border border-[var(--border)]"
                  />
                </div>
              ) : (
                <pre className="p-4 rounded-xl bg-[var(--surface)] border border-[var(--border)] font-mono text-xs text-[var(--foreground)] overflow-auto max-h-[60vh]">
                  {previewContent}
                </pre>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
