import React, { useEffect, useState } from 'react';
import {
  Files,
  RotateCw,
  Search,
  FileText,
  Presentation,
  FileSpreadsheet,
  FileCode,
  Globe,
  Download,
  Eye,
  Share2,
  Check,
} from 'lucide-react';
import { listArtifactsApi, resolveArtifactDownloadUrl, type Artifact } from '../../services/playgroundApi';

interface ArtifactsWorkspaceProps {
  onPreviewArtifact?: (art: Artifact) => void;
}

export function ArtifactsWorkspace({ onPreviewArtifact }: ArtifactsWorkspaceProps) {
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [filter, setFilter] = useState<string>('all');
  const [search, setSearch] = useState('');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const fetchArtifacts = async () => {
    setIsLoading(true);
    try {
      const data = await listArtifactsApi();
      setArtifacts(data);
    } catch (e) {
      console.error('Failed to load artifacts:', e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchArtifacts();
  }, []);

  const handleCopyLink = (art: Artifact) => {
    const url = resolveArtifactDownloadUrl(art.download_url);
    navigator.clipboard.writeText(window.location.origin + url);
    setCopiedId(art.id);
    setTimeout(() => setCopiedId(null), 1500);
  };

  const getArtifactIcon = (type: string, name: string) => {
    const upper = (type || '').toUpperCase();
    if (upper === 'PDF' || name.endsWith('.pdf')) {
      return <FileText size={20} className="text-[#F43F5E]" />;
    }
    if (upper === 'PPTX' || name.endsWith('.pptx')) {
      return <Presentation size={20} className="text-[#F59E0B]" />;
    }
    if (upper === 'CSV' || upper === 'XLSX' || name.endsWith('.csv') || name.endsWith('.xlsx')) {
      return <FileSpreadsheet size={20} className="text-[#10B981]" />;
    }
    if (upper === 'WEBSITE' || name.endsWith('.html') || name.endsWith('.htm')) {
      return <Globe size={20} className="text-[#06B6D4]" />;
    }
    return <FileCode size={20} className="text-[#3B82F6]" />;
  };

  const filtered = artifacts.filter((a) => {
    const matchesFilter =
      filter === 'all'
        ? true
        : a.type.toLowerCase().includes(filter.toLowerCase()) ||
          a.name.toLowerCase().endsWith(filter.toLowerCase());
    const matchesSearch =
      a.name.toLowerCase().includes(search.toLowerCase()) ||
      a.type.toLowerCase().includes(search.toLowerCase());
    return matchesFilter && matchesSearch;
  });

  const filterTabs = ['all', 'PDF', 'PPTX', 'HTML', 'CSV', 'CODE'];

  return (
    <div className="flex-1 flex flex-col h-full bg-[#060911] overflow-hidden p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-semibold text-[#E7EAF4] tracking-tight">Artifacts & Deliverables</h1>
          <p className="text-xs text-[#8891A8] mt-1">
            Browse and download documents, slide decks, and code generated by Asura.
          </p>
        </div>

        <button
          onClick={fetchArtifacts}
          className="p-2 rounded-lg bg-[#151C2E] border border-[#232D45] text-[#8891A8] hover:text-[#E7EAF4] transition-colors asura-btn-interactive"
          title="Refresh artifacts"
        >
          <RotateCw size={15} />
        </button>
      </div>

      {/* Filters and Search */}
      <div className="flex items-center justify-between gap-3 mb-5 flex-wrap">
        <div className="flex items-center gap-1 bg-[#0D121F] p-1 rounded-xl border border-[#232D45]">
          {filterTabs.map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`px-3 py-1 rounded-lg text-xs font-medium capitalize transition-all ${
                filter === tab
                  ? 'bg-[#151C2E] text-[#E7EAF4] font-semibold shadow-xs border border-[#232D45]'
                  : 'text-[#8891A8] hover:text-[#E7EAF4]'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-64">
          <Search size={13} className="absolute left-3 top-2.5 text-[#8891A8]" />
          <input
            type="text"
            placeholder="Search deliverables..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-8 pr-3 py-1.5 bg-[#0D121F] border border-[#232D45] rounded-xl text-xs text-[#E7EAF4] placeholder-[#8891A8] focus:outline-none focus:border-[#06B6D4]/40"
          />
        </div>
      </div>

      {/* Artifacts Grid */}
      <div className="flex-1 overflow-y-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {isLoading ? (
          <div className="col-span-full p-8 text-center text-xs text-[#8891A8]">
            Loading deliverables...
          </div>
        ) : filtered.length === 0 ? (
          <div className="col-span-full p-12 text-center text-xs text-[#8891A8] rounded-xl border border-dashed border-[#232D45]">
            No deliverables found. Deliverables are generated automatically when Asura executes tasks.
          </div>
        ) : (
          filtered.map((art) => {
            const downloadUrl = resolveArtifactDownloadUrl(art.download_url);
            const isCopied = copiedId === art.id;

            return (
              <div
                key={art.id}
                className="p-4 rounded-2xl bg-[#0D121F] border border-[#232D45] hover:border-[#06B6D4]/40 transition-all flex flex-col justify-between group asura-card-interactive shadow-xs"
              >
                <div>
                  <div className="w-10 h-10 rounded-xl bg-[#151C2E] border border-[#232D45] flex items-center justify-center mb-3">
                    {getArtifactIcon(art.type, art.name)}
                  </div>
                  <h3 className="text-sm font-semibold text-[#E7EAF4] group-hover:text-[#06B6D4] transition-colors truncate">
                    {art.name}
                  </h3>
                  <div className="text-[11px] text-[#8891A8] mt-1 flex items-center gap-2">
                    <span className="font-mono text-[10px] px-1.5 py-0.2 bg-[#151C2E] rounded border border-[#232D45] uppercase">
                      {art.type}
                    </span>
                    {art.size > 0 && <span>{(art.size / 1024).toFixed(1)} KB</span>}
                  </div>
                </div>

                <div className="mt-4 pt-3 border-t border-[#232D45]/60 flex items-center justify-end gap-1.5">
                  {onPreviewArtifact && (
                    <button
                      onClick={() => onPreviewArtifact(art)}
                      className="p-1.5 rounded-lg text-[#8891A8] hover:text-[#E7EAF4] hover:bg-[#151C2E] transition-colors"
                      title="Preview"
                    >
                      <Eye size={14} />
                    </button>
                  )}
                  <button
                    onClick={() => handleCopyLink(art)}
                    className="p-1.5 rounded-lg text-[#8891A8] hover:text-[#E7EAF4] hover:bg-[#151C2E] transition-colors"
                    title="Copy Link"
                  >
                    {isCopied ? <Check size={14} className="text-[#10B981]" /> : <Share2 size={14} />}
                  </button>
                  <a
                    href={downloadUrl}
                    download={art.name}
                    className="p-1.5 rounded-lg text-[#06B6D4] hover:bg-[#06B6D4]/10 transition-colors"
                    title="Download"
                  >
                    <Download size={14} />
                  </a>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
